import './modules/page-loading';
// import './modules/input-number-mask';
import '../pug/components/ui/main-accordeon/main-accordeon';
import '../pug/sections/reviews/reviews';
import '../pug/sections/history/history';
import '../pug/sections/winners/winners';
import '../pug/components/ui/cards/nomination-card/nomination-card';
import '../pug/layouts/base-section/base-section';
import "./modules/swiper";
import './modules/modals';
